name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - name: clone the repo
        run: | 
          git clone https://github.com/Kunal-Yelekar/bitztransights.git -y 
          remote_path: /home/ubuntu/
          remote_host: ec2-3-111-214-63.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: deploy the file in NGINX
        run: |
          sudo cp /home/ubuntu/bitztransights/kunal.html /usr/share/nginx/html/
          remote_host: ec2-3-111-214-63.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: restart the NGINX
        run: |
          sudo systemctl reload nginx
          remote_host: ec2-3-111-214-63.ap-south-1.compute.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
