name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: clone the repo
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ec2-3-111-214-63.ap-south-1.compute.amazonaws.com
          USER: ubuntu
        run: | 
          cd repo
          git clone https://github.com/Kunal-Yelekar/bitztransights.git

      - name: deploy the file in NGINX
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ec2-3-111-214-63.ap-south-1.compute.amazonaws.com
          USER: ubuntu
        run: |
          sudo cp ./bitztransights/kunal.html /usr/share/nginx/html/

      - name: restart the NGINX
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ec2-3-111-214-63.ap-south-1.compute.amazonaws.com
          USER: ubuntu
        run: |
          sudo systemctl reload nginx
